### PR TITLE
Fixes canonical link typo + getArticles comment update

### LINKED ISSUE #93: Add support for alternative canonical links
For articles we syndicate, we may be required to link back to the original piece with this tag.

We seem to already have an element in the template for canonical links.

ie - `<link rel="canonical" href="..."/>`

But they're currently just pointing by default back to the article itself.

**Work to do:**
- [x] Add a `canonical` field to the Article content model in Contentful
- [ ] Update the `createArticle.js` script to populate the `canonicalLink` attribute

### PR DESCRIPTION
**Pull request by jonuy**
#### What's this PR do?
Fixes bug where the canonical link wasn't getting set.

#### How was this tested? How should this be reviewed?
This article is the one that should have it: /articles/3-ways-to-make-better-decisions-with-the-power-of-noticing/

We can check the deploy preview to make sure it's got it.

#### What are the relevant tickets?
Closes #93

### CODE REVIEW

File: hugo/lib/getArticles.js [hunk 1]
```diff
@@ -16,7 +16,7 @@ if (
     You need to specify the environment to pull content for.
 
       Usage:
-        $ npm run fetch-content -- --staging
+        $ npm getArticles.js --staging
```
Comment (kaladin9017) [inline hugo/lib/getArticles.js]: Good catch.
